apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: steeltoe-weather
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: steeltoe-weather
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: steeltoe-weather
    app.kubernetes.io/component: run
    carto.run/workload-name: steeltoe-weather
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: steeltoe-weather
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: steeltoe-weather
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: steeltoe-weather
    spec:
      containers:
      - image: ajtanzuregistry.azurecr.io/workloads/steeltoe-weather-workloads@sha256:57e6e58c63a7ca1218f216f3e8396de085f366bc9d53f999ae72d5eac7b887d9
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

